<a href="https://colab.research.google.com/github/mangesh-trimbake/Colaboratory/blob/master/numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
#more than one dimensions
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [5]:
#minimum dimensions
a = np.array([1,2,3,4,5],ndmin = 2)
print(a)


[[1 2 3 4 5]]


In [6]:
#dtype parameter
a = np.array([1,2,3], dtype = complex)
print(a)


[1.+0.j 2.+0.j 3.+0.j]
